olist_staging:          # must match dbt_project.yml profile
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: your project-ID  # GCP project ID
      dataset: olist                  # dataset name
      threads: 4
      location: US
