olist_staging:          # must match dbt_project.yml profile
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: rock-partition-505312-a6   # GCP project ID
      dataset: ingestion                  # dataset name
      threads: 4
      location: US
