# Project configuration
name: 'olist_data_mart'
version: '1.0.0'

# Profile must match your profiles.yml
profile: 'olist_data_mart'

# File paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  olist_data_mart:
    staging:
      +materialized: view
    marts:
      +materialized: table
